# Generated by Django 5.0.6 on 2024-06-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En proceso'), ('F', 'Finalizado')], default='P', max_length=1),
        ),
    ]
