# Generated by Django 5.0.6 on 2024-07-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Administrador',
            new_name='Admin',
        ),
    ]
