# Generated by Django 5.0.6 on 2024-07-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_pedidozapatilla_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla',
            name='marca',
            field=models.CharField(max_length=100),
        ),
    ]
