# Generated by Django 5.0.6 on 2024-07-05 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_alter_zapatilla_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.direccion'),
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.marca'),
        ),
    ]
