# Generated by Django 5.0.6 on 2024-07-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_remove_usuario_direcciones_carrito_zapatilla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direcciones',
            field=models.ManyToManyField(related_name='usuarios', to='aplicacion.direccion'),
        ),
    ]
