# Generated by Django 5.0.6 on 2024-07-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_usuario_direcciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direcciones',
            field=models.ManyToManyField(to='aplicacion.direccion'),
        ),
    ]
