# Generated by Django 5.0.6 on 2024-07-08 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_remove_usuario_direccion_alter_usuario_direcciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockzapatilla',
            name='zapatilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.zapatilla'),
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.marca'),
        ),
    ]
