# Generated by Django 5.0.6 on 2024-07-08 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_alter_stockzapatilla_zapatilla_alter_zapatilla_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla',
            name='precio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(20000), django.core.validators.MaxValueValidator(500000)]),
        ),
    ]
