# Generated by Django 5.0.6 on 2024-07-08 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_alter_zapatilla_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En proceso'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='stockzapatilla',
            name='zapatilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.zapatilla'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fnac',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='zapatilla',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.marca'),
        ),
    ]
